### ISSUE TITLE
Input page formatting off and extra field 

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#536]
![image](https://cloud.githubusercontent.com/assets/8301092/25043598/1196983a-20ef-11e7-9d50-5b82198f2d08.png)

- [ ] We should only display the first four fields for parameters indexed by MARS (longstanding convention for TaxBrain. 

- [ ] Also, the Head of Household field is offset from the others.

**Comment by martinholmer** [comment]
Addendum to TaxBrain issue #536: here and everywhere on the TaxBrain input page the acronym "Fica" should be fully capitalized like this "FICA".  The current usage makes it look to some people like we aren't familiar with payroll taxes, which is not a good impression to leave with people.

**Comment by MattHJensen** [comment]
> Addendum to TaxBrain issue #536: here and everywhere on the TaxBrain input page the acronym "Fica" should be fully capitalized like this "FICA". The current usage makes it look to some people like we aren't familiar with payroll taxes, which is not a good impression to leave with people.

Thanks @martinholmer. To be more specific: 

- [ ] the TaxBrain input page should maintain the capitalization in current_law_policy.json, from which section names are pulled. 

In current_law_policy.json:  ```"section_2": "Additional Medicare FICA",```

**Comment by brittainhard** [comment]
The capitalization issue has been solved in https://github.com/open-source-economics/Tax-Calculator/pull/1298

**Comment by MattHJensen** [comment]
@brittainhard,

> The capitalization issue has been solved in open-source-economics/Tax-Calculator#1298

That is not quite true. TaxBrain does not currently display the same capitalization as is in current_law_policy.json. open-source-economics/Tax-Calculator#1298 does make the capitalization more consistent throughout current_law_policy.json, but those improvements will not make their way to TaxBrain without a fix to webapp-public that guarantees that current_law_policy.json capitalization is not modified by webapp-public.

**Comment by brittainhard** [comment]
Good point @MattHJensen. I'll take out the template tags that capitalize the section names. I'll include it with the fix that hides the widow field.

**Comment by MattHJensen** [comment]
@brittainhard, I reopened this because the capitalization for section headers is still not pulled properly from tax-calculator.

**Comment by MattHJensen** [comment]
@brittainhard, just want to check in again on this one as it is outstanding from 2.5.

**Comment by MattHJensen** [comment]
Closing in favor of #633.
